# Generated by Django 4.2.7 on 2026-02-17 07:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('file', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
