# Generated by Django 4.2.7 on 2026-02-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='processed_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
