# Generated by Django 4.2.7 on 2026-03-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricealert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='product_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='query',
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
